version: '3'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  server:
    build: server
    environment:
      - PORT=5000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:3000
      - JWT_SECRET=wIYOVtqnTg8aRcurGLva
      - MONGO_URI=mongodb://localhost:27017/?readPreference=primary&directConnection=true&ssl=false
    ports:
      - '5000:5000'
