version: '3'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  server:
    build: server
    environment:
      - PORT=5000
      - BASE_API_URL=api
      - CLIENT_URL=http://localhost:3000
      - JWT_SECRET=wIYOVtqnTg8aRcurGLva
      - SESSION_SECRET=BF94Zoyz0WHzd9DegJC9
      - MONGO_URI=mongodb+srv://admin-terence:5HRXS4naQwThtap7@cluster0.l1zh8kf.mongodb.net/?retryWrites=true&w=majority
    ports:
      - '5000:5000'
